#!/bin/bash

if [ -f node_modules/aws-sdk/lib/_aws.js ]; then
  exit 0
fi

bun install --production --frozen-lockfile

mv node_modules/aws-sdk/lib/aws.js node_modules/aws-sdk/lib/_aws.js

cat > node_modules/aws-sdk/lib/aws.js <<'EOF'
const AWS = require('./_aws');

AWS.config.update({
  endpoint: `http://${process.env.LOCALSTACK_HOSTNAME}:${process.env.EDGE_PORT}/`,
  s3ForcePathStyle: true
});

module.exports = AWS;
EOF
