mutation(
  $accession_number: String!
  $role: FileSetRole!
  $metadata: FileSetMetadataInput!
  $work_id: ID!
) {
  createFileSet(
    accessionNumber: $accession_number
    role: $role
    metadata: $metadata
    workId: $work_id
  ) {
    id
  }
}
