fragment FileSetFields on FileSet {
  id
  accessionNumber
  role {
    id
    label
    scheme
  }
  rank
  position
  metadata {
    description
    sha256
    label
    location
    original_filename
  }
}
