fragment FileSetFields on FileSet {
  id
  accessionNumber
  role {
    id
    label
    scheme
  }
  rank
  position
  streamingUrl
  coreMetadata {
    description
    sha256
    label
    location
    originalFilename
  }
  extractedMetadata
}
