fragment FileSetFields on FileSet {
  id
  accessionNumber
  role {
    id
    label
    scheme
  }
  rank
  position
  posterOffset
  representativeImageUrl
  streamingUrl
  structuralMetadata {
    type
    value
  }
  coreMetadata {
    description
    digests {
      md5
    }
    label
    location
    originalFilename
  }
  extractedMetadata
}
