mutation(
  $accession_number: String!
  $role: FileSetRole!
  $coreMetadata: FileSetCoreMetadataInput!
  $work_id: ID!
) {
  ingestFileSet(
    accessionNumber: $accession_number
    role: $role
    coreMetadata: $coreMetadata
    workId: $work_id
  ) {
    id
  }
}
