fragment WorkFields on Work {
  id
  accessionNumber
  collection {
    id
    name
  }
  fileSets {
    ...FileSetFields
  }
  insertedAt
  manifestUrl
  project {
    id
    name
  }
  published
  representativeImage
  sheet {
    id
    name
  }
  updatedAt
  visibility {
    id
    label
  }
  workType {
    id
    label
  }
  ...WorkAdministrativeMetadataFields
  ...WorkDescriptiveMetadataFields
}
