fragment WorkFields on Work {
  id
  accessionNumber
  representativeImage
  visibility
  workType
  fileSets {
    ...FileSetFields
  }
  administrativeMetadata {
    preservationLevel
    rightsStatement
  }
  descriptiveMetadata {
    title
    description
  }
}
