fragment WorkAdministrativeMetadataFields on Work {
  administrativeMetadata {
    libraryUnit {
      id
      label
    }
    preservationLevel {
      id
      label
    }
    status {
      id
      label
    }
  }
}
