fragment WorkFields on Work {
  id
  accessionNumber
  collection {
    id
    title
  }
  fileSets {
    ...FileSetFields
  }
  insertedAt
  manifestUrl
  project {
    id
    title
  }
  published
  readingRoom
  representativeImage
  ingest_sheet {
    id
    title
  }
  updatedAt
  visibility {
    id
    label
  }
  workType {
    id
    label
  }
  ...WorkAdministrativeMetadataFields
  ...WorkDescriptiveMetadataFields
}
