defmodule Meadow.Data.Schemas.ValueEntry do
  @moduledoc """
  An identified free-text value for a repeating descriptive-metadata field.

  Each entry carries a stable `id` so per-item provenance can be attached to the
  item itself rather than recovered from list order or string comparison. The id
  is minted once (autogenerated) and preserved across edits whenever it is echoed
  back in the params, exactly like the other embedded metadata entries.

  For backwards compatibility the changeset also accepts a bare string (e.g. from
  CSV import or the AI apply path), normalizing it to `%{"value" => string}` so
  existing callers that pass `["a", "b"]` keep working and simply gain ids.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  embedded_schema do
    field :value, :string
  end

  def changeset(entry \\ %__MODULE__{}, params) do
    entry
    |> cast(normalize(params), [:id, :value])
    |> validate_required([:value])
  end

  @doc """
  Normalize a single field value into entry params. A bare string becomes
  `%{"value" => string}`; a map is passed through unchanged.
  """
  def normalize(value) when is_binary(value), do: %{"value" => value}
  def normalize(%{} = params), do: params
  def normalize(other), do: other

  @doc """
  Flatten a list of entries (or already-flat strings) back to plain strings, used
  at the public boundaries (search index, CSV) so those representations are
  unchanged by the introduction of identity.
  """
  def values(nil), do: []
  def values(list) when is_list(list), do: Enum.map(list, &value/1)

  defp value(%__MODULE__{value: value}), do: value
  defp value(%{value: value}), do: value
  defp value(%{"value" => value}), do: value
  defp value(value) when is_binary(value), do: value
end
