defmodule Meadow.Data.Schemas.ValueEntry do
  @moduledoc """
  An identified free-text value for a repeating descriptive-metadata field.

  Each entry carries a stable `id` so per-item provenance can be attached to the
  item itself rather than recovered from list order or string comparison. The id
  is minted once (autogenerated) and preserved across edits whenever it is echoed
  back in the params, exactly like the other embedded metadata entries. Params
  sent as bare values (no id) additionally keep their identity when the value
  exactly matches a current entry — see
  `WorkDescriptiveMetadata.changeset/2` — so id-less callers re-sending an
  unchanged list don't churn ids.

  For backwards compatibility the changeset also accepts a bare string (e.g. from
  CSV import or the AI apply path), normalizing it to `%{"value" => string}` so
  existing callers that pass `["a", "b"]` keep working and simply gain ids.
  """

  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  embedded_schema do
    field :value, :string
  end

  def changeset(entry \\ %__MODULE__{}, params) do
    entry
    |> cast(normalize(params), [:id, :value])
    |> validate_required([:value])
  end

  @doc """
  Normalize a single field value into entry params. A bare string becomes
  `%{"value" => string}`; a map is passed through unchanged.
  """
  def normalize(value) when is_binary(value), do: %{"value" => value}
  def normalize(%{} = params), do: params
  def normalize(other), do: other

  @doc """
  Decode one CSV cell item, the counterpart of `to_csv_string/1`. Exported items
  carry their stable id as a `uuid:` prefix (the same `prefix:content` cell
  convention notes and related URLs use), so an edited value keeps its identity
  through a CSV round trip. A UUID is a strict 36-character recognizer, so free
  text that merely contains — or even starts with — a colon can never be
  misparsed: anything without the prefix decodes to the bare value it is,
  keeping its existing id on save when the value is unchanged (exact-value
  rehydration) or minting a fresh one when it's new.
  """
  def from_string(""), do: nil

  def from_string(value) when is_binary(value) do
    with [maybe_id, rest] <- String.split(value, ":", parts: 2),
         {:ok, id} <- cast_uuid(maybe_id) do
      %{id: id, value: rest}
    else
      _ -> value
    end
  end

  @doc """
  Encode one entry for a CSV cell: `uuid:value`, or the bare value for an entry
  that (pre-backfill) has no id. Unrecognizable shapes encode as nil rather than
  failing the row.
  """
  def to_csv_string(%{id: id, value: value}) when is_binary(id) and id != "",
    do: "#{id}:#{value}"

  def to_csv_string(%{"id" => id, "value" => value}) when is_binary(id) and id != "",
    do: "#{id}:#{value}"

  def to_csv_string(%{value: value}), do: value
  def to_csv_string(%{"value" => value}), do: value
  def to_csv_string(value) when is_binary(value), do: value
  def to_csv_string(_entry), do: nil

  defp cast_uuid(string) when byte_size(string) == 36,
    do: string |> String.downcase() |> Ecto.UUID.cast()

  defp cast_uuid(_string), do: :error

  @doc """
  Flatten a list of entries (or already-flat strings) back to plain strings, used
  at the public boundaries (search index, CSV) so those representations are
  unchanged by the introduction of identity.
  """
  def values(nil), do: []
  def values(list) when is_list(list), do: Enum.map(list, &value/1)

  defp value(%__MODULE__{value: value}), do: value
  defp value(%{value: value}), do: value
  defp value(%{"value" => value}), do: value
  defp value(value) when is_binary(value), do: value
end
