AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Meadow Ingest Pipeline
Parameters:
  LambdaLayerBase:
    Type: String
    Default: "s3://nul-public/lambda-layers"
Resources:
  exifToolLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: exiftool
      CompatibleRuntimes: ["nodejs16.x"]
      ContentUri: !Sub "${LambdaLayerBase}/exiftool_lambda_layer.zip"
  ffmpegLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: ffmpeg
      CompatibleRuntimes: ["nodejs16.x"]
      ContentUri: !Sub "${LambdaLayerBase}/ffmpeg.zip"
  mediaInfoLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: mediainfo
      CompatibleRuntimes: ["nodejs16.x"]
      ContentUri: !Sub "${LambdaLayerBase}/mediainfo_lambda_layer.zip"
  perlLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: perl
      CompatibleRuntimes: ["nodejs16.x"]
      ContentUri: !Sub "${LambdaLayerBase}/lambda-layer-perl-5.30.zip"
  digester:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: digester
      Description: Generate FileSet digests
      CodeUri: ./digester
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 1024
      Timeout: 240
  executeFixity:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: execute-fixity
      Description: Run the fixity step function
      CodeUri: ./execute-fixity
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Timeout: 60
      Environment:
        Variables:
          stateMachineArn: ""
  exif:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: exif
      Description: Extract EXIF metadata from FileSet
      CodeUri: ./exif
      Handler: index.handler
      Runtime: nodejs16.x
      Layers:
        - !Ref perlLayer
        - !Ref exifToolLayer
      EphemeralStorage:
        Size: 8192
      MemorySize: 768
      Timeout: 120
      Environment:
        Variables:
          EXIFTOOL: ""
  frameExtractor:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: frame-extractor
      Description: Extract frame from video
      CodeUri: ./frame-extractor
      Handler: index.handler
      Runtime: nodejs16.x
      Layers:
        - !Ref ffmpegLayer
      MemorySize: 1024
      Timeout: 240
  mediainfo:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mediainfo
      Description: Extract MediaInfo metadata from FileSet
      CodeUri: ./mediainfo
      Handler: index.handler
      Runtime: nodejs16.x
      Layers:
        - !Ref mediaInfoLayer
      MemorySize: 512
      Timeout: 240
      Environment:
        Variables:
          MEDIAINFO_PATH: ""
  mimeType:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: mime-type
      Description: Extract MIME type from FileSet
      CodeUri: ./mime-type
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 256
      Timeout: 120
  pyramidTiff:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: pyramid-tiff
      Description: Create pyramid TIFF derivative
      CodeUri: ./pyramid-tiff
      Handler: index.handler
      Runtime: nodejs16.x
      Layers:
        - !Ref ffmpegLayer
      MemorySize: 8192
      Timeout: 240
      Environment:
        Variables:
          NODE_OPTIONS: "--max-old-space-size=8192"
          VIPS_DISC_THRESHOLD: "3500m"
  streamAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: stream-authorizer
      Description: Stream authorizer
      CodeUri: ./stream-authorizer
      Handler: index.handler
      Runtime: nodejs16.x
      MemorySize: 128
      Timeout: 5
