mutation (
  $work_id: ID!
  $field_paths: [String!]!
  $item_ids: [String!]
  $reason: String
) {
  attestHumanAuthoredMetadata(
    workId: $work_id
    fieldPaths: $field_paths
    itemIds: $item_ids
    reason: $reason
  ) {
    id
    aiProvenanceSummary {
      fieldPath
      origin
      status
      latestEventType
      itemProvenance {
        id
        origin
      }
    }
  }
}
