#import "./ControlledValueFields.frag.gql"

query AuthoritiesSearch($authority: ID!, $query: String!, $limit: Int) {
  authoritiesSearch(authority: $authority, query: $query, limit: $limit) {
    ...ControlledValueFields
  }
}
