fragment CollectionFields on Collection {
  id
  title
  description
  keywords
  findingAidUrl
  adminEmail
  featured
  totalWorks
  representativeWork {
    id
    representativeImage
  }
  stats {
    total
    published
    unpublished
    image
    audio
    video
  }
}
