#import "./WorkFields.frag.gql"
#import "./FileSetFields.frag.gql"
#import "./WorkDescriptiveMetadataFields.frag.gql"
#import "./WorkAdministrativeMetadataFields.frag.gql"

mutation(
  $accessionNumber: String!
  $published: CodedTermInput!
  $descriptiveMetadata: WorkDescriptiveMetadataInput!
  $administrativeMetadata: WorkAdministrativeMetadataInput!
  $visibility: CodedTermInput!
  $workType: CodedTermInput!
) {
  createWork(
    accessionNumber: $accessionNumber
    descriptiveMetadata: $descriptiveMetadata
    administrativeMetadata: $administrativeMetadata
    published: $published
    visibility: $visibility
    workType: $workType
  ) {
    ...WorkFields
  }
}
