#import "./CollectionFields.frag.gql"

mutation($collection_id: ID!, $work_id: ID) {
  setCollectionImage(collection_id: $collection_id, work_id: $work_id) {
    ...CollectionFields
    works {
      id
      representativeImage
    }
  }
}
