#import "./FileSetFields.frag.gql"
#import "./WorkFields.frag.gql"
#import "./WorkDescriptiveMetadataFields.frag.gql"
#import "./WorkAdministrativeMetadataFields.frag.gql"

mutation($work_id: ID!, $file_set_id: ID!) {
  setWorkImage(work_id: $work_id, file_set_id: $file_set_id) {
    ...WorkFields
  }
}
