#import "./WorkFields.frag.gql"
#import "./FileSetFields.frag.gql"
#import "./WorkDescriptiveMetadataFields.frag.gql"
#import "./WorkAdministrativeMetadataFields.frag.gql"

mutation(
  $id: ID!
  $collection_id: ID!
  $descriptive_metadata: WorkDescriptiveMetadataInput!
) {
  updateWork(
    id: $id
    work: {
      collection_id: $collection_id
      descriptive_metadata: $descriptive_metadata
    }
  ) {
    ...WorkFields
  }
}
