#import "./FileSetFields.frag.gql"

mutation (
  $id: ID!
  $coreMetadata: FileSetCoreMetadataUpdate!
  $structuralMetadata: FileSetStructuralMetadataInput
) {
  updateFileSet(
    id: $id
    coreMetadata: $coreMetadata
    structuralMetadata: $structuralMetadata
  ) {
    ...FileSetFields
  }
}
