---
name: meadow-test
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.1'
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-hex-
      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-build-
      - name: Cache JS dependencies
        uses: actions/cache@v2
        with:
          path: |
            assets/node_modules
            priv/nodejs/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-
            ${{ runner.os }}-yarn-
      - name: Install Elixir dependencies
        run: mix do deps.get, deps.compile
      - name: Install JS dependencies
        run: yarn install --cwd assets
      - name: Install Lambda dependencies
        run: |
          for pkg in $(find priv/nodejs -maxdepth 2 -name yarn.lock)
          do
            echo "yarn install --cwd $(dirname $pkg)"
            yarn install --cwd $(dirname $pkg)
          done
  js-test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-hex-
      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-build-
      - name: Cache JS dependencies
        uses: actions/cache@v2
        with:
          path: |
            assets/node_modules
            priv/nodejs/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-
            ${{ runner.os }}-yarn-
      - name: JS Static Analysis
        run: yarn prettier
        working-directory: assets
      - name: JS Tests
        run: yarn ci -w 1
        working-directory: assets
      - name: Test Webpack Build
        run: yarn deploy
        working-directory: assets
  elixir-test:
    runs-on: ubuntu-latest
    needs: dependencies
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12.1'
      - name: Cache Elixir dependencies
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-hex-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-hex-
      - name: Cache Elixir build
        uses: actions/cache@v2
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('mix.lock') }}
            ${{ runner.os }}-build-
      - name: Cache JS dependencies
        uses: actions/cache@v2
        with:
          path: |
            assets/node_modules
            priv/nodejs/*/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-${{ hashFiles ('priv/nodejs/*/yarn.lock') }}
            ${{ runner.os }}-yarn-${{ hashFiles('assets/yarn.lock') }}-
            ${{ runner.os }}-yarn-
      - name: Elixir Static Analysis
        run: mix credo